version: '3.7'
services:
  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - /home/ubuntu/testing-Traefik/app:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      # HTTP router with redirect
      - traefik.http.routers.web-http.entrypoints=web
      - traefik.http.routers.web-http.rule=Host(`myapp.sesewa-devops.slimprepdevops.com`)
      - traefik.http.routers.web-http.middlewares=web-redirect-to-https
      # HTTPS router
      - traefik.http.routers.web-https.entrypoints=web-secured
      - traefik.http.routers.web-https.rule=Host(`myapp.sesewa-devops.slimprepdevops.com`)
      - traefik.http.routers.web-https.tls=true
      - traefik.http.routers.web-https.tls.certresolver=mytlschallenge
      - traefik.http.routers.web-https.tls.domains[0].main=myapp.sesewa-devops.slimprepdevops.com
      - traefik.http.routers.web-https.middlewares=web-compress
      # Middlewares
      - traefik.http.middlewares.web-redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.web-compress.compress=true
  
networks:
  default:
    external:
      name: sesewa-network